language: "kr"
pipeline:

#- name: "component.KoreanTokenizerKhaiii"
- name: "component.KoreanTokenizer"
# - name: "ner_duckling_http"
 - name: "component.KoreanDuckling"
  url: "http://0.0.0.0:8000"
  dimensions: ["duration", "timezone", "ordinal", "url", "cycle", "time", "number"]
  locale: "ko_KO"
  timezone: "Asia/Seoul"
- name: "component.KoreanExtractor"
#- name: "component.PreTrainedCRF"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
  "token_pattern": '(?u)\b\w+\b' # 1개의 character도 인식하도록 regex 변경
- name: "intent_classifier_tensorflow_embedding"
- name: "intent_entity_featurizer_regex"
