language: "kr"
pipeline:

#- name: "tokenizer_whitespace"
- name: "component.KoreanTokenizer"
#  "norm": false
#  "stem": false
#- name: "ner_crf"
- name: "component.PreTrainedCRF"
- name: "component.KoreanExtractor"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
  "token_pattern": '(?u)\b\w+\b' # 1개의 character도 인식하도록 regex 변경
- name: "intent_classifier_tensorflow_embedding"
- name: "intent_entity_featurizer_regex"
